Add options for changing colour temperature and colour for L530 bulbs
fishbigger/TapoP100 pull request #10
Opened 2021-02-16 23:51 UTC by arrival-spring

Closes #7 

Essentially the same methods as for brightness, but one for colour which takes hue and sat and one for colour temperature which takes values in kelvin.

2021-02-25 00:12 UTC, RyanWoodruff requested changes

2021-02-25 00:12 UTC, RyanWoodruff commented on PyP100/PyP100.py
> +		URL = f"http://{self.ipAddress}/app?token={self.token}"
```suggestion
		colortemp = colortemp + 2500 # allows for range of 1- 4000  
		URL = f"http://{self.ipAddress}/app?token={self.token}"
```

2021-02-25 00:14 UTC, RyanWoodruff commented on PyP100/PyP100.py
> +		URL = f"http://{self.ipAddress}/app?token={self.token}"
LGTM! - Other than the range on colortemp being a bit convoluted. through manual testing i found the range was 2500 - 6500. Small change makes the range 1 - 4000, which is a bit more intuitive imo.

2021-02-25 20:18 UTC, arrival-spring commented on PyP100/PyP100.py
> +		URL = f"http://{self.ipAddress}/app?token={self.token}"
I had found that same range too. I disagree with changing the range though. I feel it's most intuitive for this to take values in Kelvin (which is what the bulb expects), in the same way that brightness is 0-100 like the bulb is, and hue and saturation are their usual values and ranges.

2021-02-25 21:34 UTC, RyanWoodruff commented on PyP100/PyP100.py
> +		URL = f"http://{self.ipAddress}/app?token={self.token}"
Ah yes. I forgot that the app provides a range in kelvin. That would make sense now, I thought it was just some random range.

2021-03-26 11:48 UTC, ndg63276 commented on PyP100/PyP100.py
> +	def setColour(self, hue, saturation):
```suggestion
	def setColour(self, hue, saturation, brightness=None):
```
You can set brightness at the same time as hue and saturation, so it could be an optional parameter here.

2021-03-26 11:50 UTC, ndg63276 commented on PyP100/PyP100.py
> +
```suggestion

		if brightness is not None:
			Payload["params"]["brightness"] = brightness
```

2021-03-27 00:59 UTC, arrival-spring commented on PyP100/PyP100.py
> +	def setColour(self, hue, saturation):
Or maybe they should all be separate, one for brightness, one for hue, one for saturation?

2021-03-27 22:28 UTC, ndg63276 commented on PyP100/PyP100.py
> +	def setColour(self, hue, saturation):
You can't send hue without saturation, or vice versa. Gives error -1008.

2022-01-08 06:07 UTC, fishbigger commented
Sorry this has taken so long 🤣

2022-01-08 06:07 UTC, merged