Add terminalUUID in requests for supporting P105
fishbigger/TapoP100 pull request #12
Opened 2021-03-10 23:48 UTC by mochipon

Hello @fishbigger , thank you for everything you have done for this project!

I believe this library supports not only P100, but P105. I realized P105 plug will raise a '-1012' error if there is no `terminalUUID` in the request body of `turnOn` and `turnOff`. Interestingly, other requests do not require `terminalUUID`.

```python
>>> p100.login()
>>> info = json.loads(p100.getDeviceInfo())["result"]
>>> {k:v for k,v in info.items() if k in ["fw_ver", "hw_ver", "model"]}
{'fw_ver': '1.3.0 Build 20201201 Rel. 54462', 'hw_ver': '1.0.0', 'model': 'P105'}
>>> p100.turnOff()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/TapoP100/PyP100/PyP100.py", line 253, in turnOff
    errorMessage = self.errorCodes[str(errorCode)]
KeyError: '-1012'
```

I also fixed some exception handling in this commit.

2021-04-30 11:58 UTC, dthevenin requested changes
Some possible code and syntax improvements

2021-04-30 11:58 UTC, dthevenin commented on PyP100/PyP100.py
>  def getToken(email, password):
What about use the `self.terminalUUID` built in the `init` function in the Payload, line 22?

2021-04-30 11:58 UTC, dthevenin commented on PyP100/PyP100.py
>  def getToken(email, password):
It's not part of the PR, but the indentation is off line 17 to 23
Could be nice to fix that

2021-04-30 11:58 UTC, dthevenin commented on PyP100/PyP100.py
>  def getToken(email, password):
there are empty line code to remove line 283-285.

2021-04-30 11:59 UTC, dthevenin commented
I did test the code and the issue is fixed for P105.

2021-05-02 06:15 UTC, mochipon commented on PyP100/PyP100.py
>  def getToken(email, password):
Thank you for the comments! Actually, I don't know how this UUID were generated. 
https://github.com/fishbigger/TapoP100/blob/8d31ab7b474c234ea085eaa81ab36bda9b4fb03c/PyP100/PyP100.py#L21

IMHO, I am afraid that using a specific UUID may create the risk of being taken action to ban this UUID, or this library.

2021-05-02 23:46 UTC, dthevenin commented on PyP100/PyP100.py
>  def getToken(email, password):
Make sense. The let's keep like that.

2021-05-02 23:49 UTC, dthevenin commented
Thanks for the changes @mochipon.
I think we should merge it, since it does work as expected and it makes P105 switch works.
What do you think @fishbigger?

2021-05-02 23:50 UTC, dthevenin approved these changes
LGTM

2021-05-03 12:26 UTC, fishbigger commented
Looks like these changes should work I'll try and get them merged soon.

2021-05-03 14:51 UTC, merged